# -*- coding: utf-8 -*-
"""attendance_tracker_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPxzNV_ASj9pzMV5K9LZYgR6xwEd9Pb3

# **Attendance Tracker**

Track the attendance of students in a class for a week.

The user enters the number of students and marks attendance (P for Present, A for Absent) for each day.

Display the attendance summary at the end.
"""

num_student = input("Enter a number: ")

# Validate student number input
while not num_student.isdigit():
    print("That's not a valid number! Please try again.")
    num_student = input("Enter a number: ")

num_student = int(num_student)  # Convert to integer after validation

for student in range(1, num_student + 1):
    print(f"\nAttendance for Student {student}:")
    attendance_count_present = 0
    attendance_count_absent = 0

    for day in range(1, 8):
        while True:  # Loop until valid input is entered
            attendance = input(f"  Day {day} (P/A): ").strip().upper()
            if attendance == "P":
                attendance_count_present += 1
                break  # Exit the loop if input is valid
            elif attendance == "A":
                attendance_count_absent += 1
                break  # Exit the loop if input is valid
            else:
                print("  Invalid input. Please enter 'P' for present or 'A' for absent.")

    # Print results for the student after all days are entered
    print(f"Total Present Days: {attendance_count_present}\nTotal Absent Days: {attendance_count_absent}")